[[redirects]]
  from = "/fun/*"
  to = "https://trusting-hermann-ed5953.netlify.app/.netlify/functions/render/:route"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false