version: "2"

services:
  web:
    environment:
      DEBUG: 'true'
  node:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
  nginx:
    environment:
      REACT_DEFAULT_HOST: 'localhost'
      API_DEFAULT_HOST: 'api.localhost'
  celeryworker:
    environment:
      DEBUG: 'true'
  celerybeat:
    environment:
      DEBUG: 'true'
