version: "2"

services:
  web:
    restart: always
    build: ./backend
    image: webworkerimage
    working_dir: /usr/src/app
    expose:
      - "8000"
    volumes:
      - ./backend:/usr/src/app
      - ./backups:/usr/src/backups
      - /usr/src/app/static
      - mediadata:/usr/src/app/media
    env_file: .env
    environment:
      VIRTUAL_HOST: 'backend'
    command: /usr/local/bin/gunicorn backend.wsgi:application -w 4 -b 0.0.0.0:8000 --reload --log-level debug
    stdin_open: true
    tty: true
    networks:
      - api-tier

  nginx:
    restart: always
    build: ./nginx
    container_name: poap-fun-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/sites-enabled:/etc/nginx
      - /var/run/docker.sock:/tmp/docker.sock:ro
    volumes_from:
      - web
    depends_on:
      - web
    links:
      - web
    networks:
      - api-tier

volumes:
  mediadata:

networks:
  api-tier:
    driver: bridge
